apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourdrive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yourdrive
  template:
    metadata:
      labels:
        app: yourdrive
    spec:
      containers:
        - name: springboot
          image: rs481441/yourdrive
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: yourdrive
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: yourdrive
